import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main style={{ padding: 32 }}>{children}</main>
      </body>
    </html>
  );
}
