import type { Metadata } from "next";
import "../styles/globals.css";
export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
