import type { Metadata } from "next";
import { notFound } from "next/navigation";

import "../../styles/globals.css";
import i18nConfig from "../../../i18nConfig";
export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const locale = (await params).locale;

  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  }
  return (
    <html lang={locale} className="dark">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
